<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('brands')->truncate();
        DB::table('brands')->insert([
            [
                'id' => 1,
                'name' => 'ন্যাশনাল',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'ব্লু স্টার',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'নামিরা',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'রেড স্টার',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'মাসুম',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'সি স্টার',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'কপোতাক্ষ',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'বিসমিল্লাহ',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'কক্সবাজার',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'আল আকসা',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'বলাকা',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'সোনালী',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'বোরাক',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'রাইসা',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'গোল্ডেন',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'এ আর সি',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'মডার্ন',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'বেলি',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'ফাইভ স্টার',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'বেঙ্গল বে',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'গোল্ডেন ১',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'নিউ সোনালী',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'name' => 'লাবিব',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'name' =>'হোয়াইট গোল্ড',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'name' =>'গোল্ড কোস্ট',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'name' =>'পপুলার',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'name' =>'নিউ যমুনা',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'name' =>'রেডিয়েন্ট',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'name' =>'রংধনু',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'name' =>'সোনা মুখ',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'name' =>'নিউ সোনামুখ',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'name' =>'পদ্মা',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'name' =>'মেঘনা',
                "central_id" => 1,
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2023-06-30 11:35:52',
                'updated_at' => '2023-06-30 11:35:52',
                'deleted_at' => null,
            ],
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
