<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('items')->truncate();
        DB::table('items')->insert([
            [
                'id' => 1,
                'name' => 'বাগদা পোনা',
                'slug' => 'larvae-bagda-sale',
                'type' => 'sale',
                'parent_id' => NULL,
                'item_type' => 'larvae',
                'description' => NULL,
                'display_order' => 1,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 2,
                'name' => 'ভেনামি পোনা',
                'slug' => 'larvae-venami-sale',
                'type' => 'sale',
                'parent_id' => NULL,
                'item_type' => 'larvae',
                'description' => NULL,
                'display_order' => 2,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 3,
                'name' => 'বাগদা নফলি',
                'slug' => 'larvae-bagda-nofli-sale',
                'type' => 'sale',
                'parent_id' => NULL,
                'item_type' => 'larvae',              'description' => NULL,
                'display_order' => 3,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 4,
                'name' => 'ভেনামি নফলি',
                'slug' => 'larvae-venami-nofli-sale',
                'type' => 'sale',
                'parent_id' => NULL,
                'item_type' => 'larvae',              'description' => NULL,
                'display_order' => 4,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 5,
                'name' => 'বাগদা মাদার',
                'slug' => 'larve-bagda-mother-sale',
                'type' => 'sale',
                'parent_id' => NULL,
                'item_type' => 'larvae',              'description' => NULL,
                'display_order' => 3,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 6,
                'name' => 'ভেনামি মাদার',
                'slug' => 'larvae-venami-mother-sale',
                'type' => 'sale',
                'parent_id' => NULL,
                'item_type' => 'larvae',              'description' => NULL,
                'display_order' => 2,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 7,
                'name' => 'পুরাতন মালমাল',
                'slug' => 'old-goods-sale',
                'type' => 'sale',
                'parent_id' => NULL,
                'item_type' => 'others',              'description' => NULL,
                'display_order' => 4,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 8,
                'name' => 'জেনারেটর',
                'slug' => 'generator-sale',
                'type' => 'sale',
                'parent_id' => NULL,
                'item_type' => 'others',              'description' => NULL,
                'display_order' => 5,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 9,
                'name' => 'অন্যান্য',
                'slug' => 'others-sale',
                'type' => 'sale',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 5,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            // other sale item will be added here


            //purchase
            [
                'id' => 19,
                'name' => 'বাগদা পোনা',
                'slug' => 'larvae-bagda-purchase',
                'type' => 'purchase',
                'parent_id' => NULL,
                'item_type' => 'larvae',
                'description' => NULL,
                'display_order' => 1,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 20,
                'name' => 'ভেনামি পোনা',
                'slug' => 'larvae-venami-purchase',
                'type' => 'purchase',
                'parent_id' => NULL,
                'item_type' => 'larvae',
                'description' => NULL,
                'display_order' => 2,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 21,
                'name' => 'বাগদা মাদার',
                'slug' => 'larvae-bagda-mother-purchase',
                'type' => 'purchase',
                'parent_id' => NULL,
                'item_type' => 'larvae',              'description' => NULL,
                'display_order' => 7,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 22,
                'name' => 'ভেনামি মাদার',
                'slug' => 'larvae-venami-mother-purchase',
                'type' => 'purchase',
                'parent_id' => NULL,
                'item_type' => 'larvae',              'description' => NULL,
                'display_order' => 2,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 23,
                'name' => 'বাগদা নফলি',
                'slug' => 'larvae-bagda-nofli-purchase',
                'type' => 'purchase',
                'parent_id' => NULL,
                'item_type' => 'larvae',              'description' => NULL,
                'display_order' => 3,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 24,
                'name' => 'ভেনামি নফলি',
                'slug' => 'larvae-venami-nofli-purchase',
                'type' => 'purchase',
                'parent_id' => NULL,
                'item_type' => 'larvae',              'description' => NULL,
                'display_order' => 4,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 25,
                'name' => 'সার/ঔষধ',
                'slug' => 'fertilizer-medicine-purchase',
                'item_type' => 'others',
                'type' => 'purchase',
                'parent_id' => NULL,              'description' => NULL,
                'display_order' => 6,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 26,
                'name' => 'মাছের খাবার',
                'slug' => 'fish-food-purchase',
                'type' => 'purchase',
                'parent_id' => NULL,
                'central_id' => 1,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 8,
                'note' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 27,
                'name' => 'সরঞ্জাম',
                'slug' => 'tools',
                'type' => 'expense',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 14,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 10,
                'name' => 'অফিস খরচ',
                'slug' => 'house-expense',
                'type' => 'expense',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 9,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 11,
                'name' => 'কর্মচারী বেতন',
                'slug' => 'employee-salary-expense',
                'type' => 'expense',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 10,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 0,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 12,
                'name' => 'দিন-মজুর',
                'slug' => 'day-labour-expense',
                'type' => 'expense',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 11,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 13,
                'name' => 'পরিবহন খরচ',
                'slug' => 'transportation-expense',
                'type' => 'expense',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 12,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 14,
                'name' => 'কমিশন',
                'slug' => 'commission-expense',
                'type' => 'expense',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 13,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 15,
                'name' => 'সরঞ্জাম',
                'slug' => 'tools-expense',
                'type' => 'expense',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 14,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 1,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 16,
                'name' => 'সাপ্লাইয়ার পেমেন্ট',
                'slug' => 'supplier-payment-expense',
                'type' => 'expense',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 15,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 0,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL,
            ],
            [
                'id' => 17,
                'name' => 'অন্যান্য',
                'slug' => 'others-purchase',
                'type' => 'purchase',
                'parent_id' => NULL,
                'item_type' => 'others',
                'description' => NULL,
                'display_order' => 16,
                'note' => NULL,
                'central_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'is_active' => 0,
                'created_at' => '2023-06-30 11:35:51',
                'updated_at' => '2023-06-30 11:35:51',
                'deleted_at' => NULL,
                'deleted_by' => NULL
            ]
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
