<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('permissions')->truncate();

        $permissions = [
            [
                'id' => 1,
                'name' => 'can-create-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
                'central_id' => 1,
            ],
            [
                'id' => 2,
                'name' => 'can-edit-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
                'central_id' => 2,
            ],
            [
                'id' => 3,
                'name' => 'can-delete-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
                'central_id' => 3,
            ],
            [
                'id' => 4,
                'name' => 'can-view-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
                'central_id' => 4,
            ],
            [
                'id' => 5,
                'name' => 'can-view-details-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
                'central_id' => 5,
            ],
            [
                'id' => 6,
                'name' => 'can-create-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
                'central_id' => 6,
            ],
            [
                'id' => 7,
                'name' => 'can-edit-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
                'central_id' => 7,
            ],
            [
                'id' => 8,
                'name' => 'can-delete-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
                'central_id' => 8,
            ],
            [
                'id' => 9,
                'name' => 'can-view-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
                'central_id' => 9,
            ],
            [
                'id' => 10,
                'name' => 'can-view-details-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
                'central_id' => 10,
            ],
            [
                'id' => 11,
                'name' => 'can-create-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
                'central_id' => 11,
            ],
            [
                'id' => 12,
                'name' => 'can-edit-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
                'central_id' => 12,
            ],
            [
                'id' => 13,
                'central_id' => 13,
                'name' => 'can-delete-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 14,
                'name' => 'can-view-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
                'central_id' => 14,
            ],

            [
                'id' => 15,
                'central_id' => 15,
                'name' => 'can-create-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 16,
                'central_id' => 16,
                'name' => 'can-edit-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 17,
                'central_id' => 17,
                'name' => 'can-delete-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 18,
                'central_id' => 18,
                'name' => 'can-view-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 19,
                'central_id' => 19,
                'name' => 'can-view-details-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 20,
                'central_id' => 20,
                'name' => 'can-create-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 21,
                'central_id' => 21,
                'name' => 'can-edit-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 22,
                'central_id' => 22,
                'name' => 'can-delete-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 23,
                'central_id' => 23,
                'name' => 'can-view-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 24,
                'central_id' => 24,
                'name' => 'can-view-details-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 25,
                'central_id' => 25,
                'name' => 'can-create-attendance',
                'guard_name' => 'web',
                'group_name' => 'Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 26,
                'central_id' => 26,
                'name' => 'can-edit-attendance',
                'guard_name' => 'web',
                'group_name' => 'Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 27,
                'central_id' => 27,
                'name' => 'can-delete-attendance',
                'guard_name' => 'web',
                'group_name' => 'Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 28,
                'central_id' => 28,
                'name' => 'can-view-attendance',
                'guard_name' => 'web',
                'group_name' => 'Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 29,
                'central_id' => 29,
                'name' => 'can-view-employee-attendance',
                'guard_name' => 'web',
                'group_name' => 'Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 30,
                'central_id' => 30,
                'name' => 'can-view-configuration',
                'guard_name' => 'web',
                'group_name' => 'Configuration Management',
                'is_active' => true,
            ],
            [
                'id' => 31,
                'central_id' => 31,
                'name' => 'can-edit-configuration',
                'guard_name' => 'web',
                'group_name' => 'Configuration Management',
                'is_active' => true,
            ],
            [
                'id' => 32,
                'central_id' => 32,
                'name' => 'can-view-sale-report',
                'guard_name' => 'web',
                'group_name' => 'Report Management',
                'is_active' => true,
            ],
            [
                'id' => 33,
                'central_id' => 33,
                'name' => 'can-view-purchase-report',
                'guard_name' => 'web',
                'group_name' => 'Report Management',
                'is_active' => true,
            ],
            [
                'id' => 34,
                'central_id' => 34,
                'name' => 'can-view-subscription',
                'guard_name' => 'web',
                'group_name' => 'Subscription Management',
                'is_active' => true,
            ],
            [
                'id' => 35,
                'central_id' => 35,
                'name' => 'can-edit-subscription',
                'guard_name' => 'web',
                'group_name' => 'Subscription Management',
                'is_active' => true,
            ],
            [
                'id' => 36,
                'central_id' => 36,
                'name' => 'can-view-item',
                'guard_name' => 'web',
                'group_name' => 'Item Management',
                'is_active' => true,
            ],
            [
                'id' => 37,
                'central_id' => 37,
                'name' => 'can-create-item',
                'guard_name' => 'web',
                'group_name' => 'Item Management',
                'is_active' => true,
            ],
            [
                'id' => 38,
                'central_id' => 38,
                'name' => 'can-edit-item',
                'guard_name' => 'web',
                'group_name' => 'Item Management',
                'is_active' => true,
            ],
            [
                'id' => 39,
                'central_id' => 39,
                'name' => 'can-delete-item',
                'guard_name' => 'web',
                'group_name' => 'Item Management',
                'is_active' => true,
            ],
            [
                'id' => 40,
                'central_id' => 40,
                'name' => 'can-create-buyer',
                'guard_name' => 'web',
                'group_name' => 'Buyer Management',
                'is_active' => true,
            ],
            [
                'id' => 41,
                'central_id' => 41,
                'name' => 'can-edit-buyer',
                'guard_name' => 'web',
                'group_name' => 'Buyer Management',
                'is_active' => true,
            ],
            [
                'id' => 42,
                'central_id' => 42,
                'name' => 'can-delete-buyer',
                'guard_name' => 'web',
                'group_name' => 'Buyer Management',
                'is_active' => true,
            ],
            [
                'id' => 43,
                'central_id' => 43,
                'name' => 'can-view-buyer',
                'guard_name' => 'web',
                'group_name' => 'Buyer Management',
                'is_active' => true,
            ],
            [
                'id' => 44,
                'central_id' => 44,
                'name' => 'can-view-details-buyer',
                'guard_name' => 'web',
                'group_name' => 'Buyer Management',
                'is_active' => true,
            ],
            [
                'id' => 45,
                'central_id' => 45,
                'name' => 'can-create-fiscal-year',
                'guard_name' => 'web',
                'group_name' => 'Fiscal Year Management',
                'is_active' => true,
            ],
            [
                'id' => 46,
                'central_id' => 46,
                'name' => 'can-view-fiscal-year',
                'guard_name' => 'web',
                'group_name' => 'Fiscal Year Management',
                'is_active' => true,
            ],
            [
                'id' => 47,
                'central_id' => 47,
                'name' => 'can-view-details-fiscal-year',
                'guard_name' => 'web',
                'group_name' => 'Fiscal Year Management',
                'is_active' => true,
            ],
            [
                'id' => 48,
                'central_id' => 48,
                'name' => 'can-edit-fiscal-year',
                'guard_name' => 'web',
                'group_name' => 'Fiscal Year Management',
                'is_active' => true,
            ],

            [
                'id' => 49,
                'central_id' => 49,
                'name' => 'can-delete-fiscal-year',
                'guard_name' => 'web',
                'group_name' => 'Fiscal Year Management',
                'is_active' => true,
            ],
            [
                'id' => 50,
                'central_id' => 50,
                'name' => 'can-create-buyer-payment',
                'guard_name' => 'web',
                'group_name' => 'Buyer Payment Management',
                'is_active' => true,
            ],
            [
                'id' => 51,
                'central_id' => 51,
                'name' => 'can-view-buyer-payment',
                'guard_name' => 'web',
                'group_name' => 'Buyer Payment Management',
                'is_active' => true,
            ],
            [
                'id' => 52,
                'central_id' => 52,
                'name' => 'can-edit-buyer-payment',
                'guard_name' => 'web',
                'group_name' => 'Buyer Payment Management',
                'is_active' => true,
            ],
            [
                'id' => 53,
                'central_id' => 53,
                'name' => 'can-delete-buyer-payment',
                'guard_name' => 'web',
                'group_name' => 'Buyer Payment Management',
                'is_active' => true,
            ],
            [
                'id' => 54,
                'central_id' => 54,
                'name' => 'can-view-sale',
                'guard_name' => 'web',
                'group_name' => 'Order Management',
                'is_active' => true,
            ],
            [
                'id' => 55,
                'central_id' => 55,
                'name' => 'can-create-sale',
                'guard_name' => 'web',
                'group_name' => 'Order Management',
                'is_active' => true,
            ],
            [
                'id' => 56,
                'central_id' => 56,
                'name' => 'can-edit-sale',
                'guard_name' => 'web',
                'group_name' => 'Order Management',
                'is_active' => true,
            ],
            [
                'id' => 57,
                'central_id' => 57,
                'name' => 'can-delete-sale',
                'guard_name' => 'web',
                'group_name' => 'Order Management',
                'is_active' => true,
            ],
            [
                'id' => 58,
                'central_id' => 58,
                'name' => 'can-view-brand',
                'guard_name' => 'web',
                'group_name' => 'Brand Management',
                'is_active' => true,
            ],
            [
                'id' => 59,
                'central_id' => 59,
                'name' => 'can-create-brand',
                'guard_name' => 'web',
                'group_name' => 'Brand Management',
                'is_active' => true,
            ],
            [
                'id' => 60,
                'central_id' => 60,
                'name' => 'can-edit-brand',
                'guard_name' => 'web',
                'group_name' => 'Brand Management',
                'is_active' => true,
            ],
            [
                'id' => 61,
                'central_id' => 61,
                'name' => 'can-delete-brand',
                'guard_name' => 'web',
                'group_name' => 'Brand Management',
                'is_active' => true,
            ],
            [
                'id' => 62,
                'central_id' => 62,
                'name' => 'can-view-atAGlance',
                'guard_name' => 'web',
                'group_name' => 'Report Management',
                'is_active' => true,
            ],
            [
                'id' => 63,
                'central_id' => 63,
                'name' => 'can-view-sms-dashboard',
                'guard_name' => 'web',
                'group_name' => 'SMS Management',
                'is_active' => true,
            ],
            [
                'id' => 64,
                'central_id' => 64,
                'name' => 'can-purchase-sms',
                'guard_name' => 'web',
                'group_name' => 'SMS Management',
                'is_active' => true,
            ],
            [
                'id' => 65,
                'central_id' => 65,
                'name' => 'can-view-purchase-sms-history',
                'guard_name' => 'web',
                'group_name' => 'SMS Management',
                'is_active' => true,
            ],
            [
                'id' => 66,
                'central_id' => 66,
                'name' => 'can-view-sms-template',
                'guard_name' => 'web',
                'group_name' => 'SMS Management',
                'is_active' => true,
            ],
            [
                'id' => 67,
                'central_id' => 67,
                'name' => 'can-view-sms-log',
                'guard_name' => 'web',
                'group_name' => 'SMS Management',
                'is_active' => true,
            ],

            [
                'id' => 68,
                'central_id' => 68,
                'name' => 'can-send-sms',
                'guard_name' => 'web',
                'group_name' => 'SMS Management',
                'is_active' => true,
            ],
            [
                'id' => 69,
                'central_id' => 69,
                'name' => 'can-view-expense',
                'guard_name' => 'web',
                'group_name' => 'Expense Management',
                'is_active' => true,
            ],
            [
                'id' => 70,
                'central_id' => 70,
                'name' => 'can-create-expense',
                'guard_name' => 'web',
                'group_name' => 'Expense Management',
                'is_active' => true,
            ],
            [
                'id' => 71,
                'central_id' => 71,
                'name' => 'can-edit-expense',
                'guard_name' => 'web',
                'group_name' => 'Expense Management',
                'is_active' => true,
            ],
            [
                'id' => 72,
                'central_id' => 73,
                'name' => 'can-delete-expense',
                'guard_name' => 'web',
                'group_name' => 'Expense Management',
                'is_active' => true,
            ],
            [
                'id' => 73,
                'central_id' => 73,
                'name' => 'can-view-buyer-due',
                'guard_name' => 'web',
                'group_name' => 'Report Management',
                'is_active' => true,
            ],
            [
                'id' => 74,
                'central_id' => 74,
                'name' => 'can-create-sms-template',
                'guard_name' => 'web',
                'group_name' => 'SMS Templates',
                'is_active' => true,
            ],
            [
                'id' => 75,
                'central_id' => 75,
                'name' => 'can-edit-sms-template',
                'guard_name' => 'web',
                'group_name' => 'SMS Templates',
                'is_active' => true,
            ],
            [
                'id' => 76,
                'central_id' => 76,
                'name' => 'can-delete-sms-template',
                'guard_name' => 'web',
                'group_name' => 'SMS Templates',
                'is_active' => true,
            ],
            // supplier
            [
                'id' => 77,
                'central_id' => 77,
                'name' => 'can-create-supplier',
                'guard_name' => 'web',
                'group_name' => 'Supplier Management',
                'is_active' => true,
            ],
            [
                'id' => 78,
                'central_id' => 78,
                'name' => 'can-edit-supplier',
                'guard_name' => 'web',
                'group_name' => 'Supplier Management',
                'is_active' => true,
            ],
            [
                'id' => 79,
                'central_id' => 79,
                'name' => 'can-delete-supplier',
                'guard_name' => 'web',
                'group_name' => 'Supplier Management',
                'is_active' => true,
            ],
            [
                'id' => 80,
                'central_id' => 80,
                'name' => 'can-view-supplier',
                'guard_name' => 'web',
                'group_name' => 'Supplier Management',
                'is_active' => true,
            ],
            [
                'id' => 81,
                'central_id' => 81,
                'name' => 'can-view-details-supplier',
                'guard_name' => 'web',
                'group_name' => 'Supplier Management',
                'is_active' => true,
            ],
            [
                'id' => 82,
                'central_id' => 82,
                'name' => 'can-create-supplier-payment',
                'guard_name' => 'web',
                'group_name' => 'Supplier Payment Management',
                'is_active' => true,
            ],
            [
                'id' => 83,
                'central_id' => 83,
                'name' => 'can-view-supplier-payment',
                'guard_name' => 'web',
                'group_name' => 'Supplier Payment Management',
                'is_active' => true,
            ],
            [
                'id' => 84,
                'central_id' => 84,
                'name' => 'can-edit-supplier-payment',
                'guard_name' => 'web',
                'group_name' => 'Supplier Payment Management',
                'is_active' => true,
            ],
            [
                'id' => 85,
                'central_id' => 85,
                'name' => 'can-delete-supplier-payment',
                'guard_name' => 'web',
                'group_name' => 'Supplier Payment Management',
                'is_active' => true,
            ],
            [
                'id' => 86,
                'central_id' => 86,
                'name' => 'can-view-supplier-due',
                'guard_name' => 'web',
                'group_name' => 'Report Management',
                'is_active' => true,
            ],
            //purchase
            [
                'id' => 87,
                'central_id' => 87,
                'name' => 'can-create-purchase',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 88,
                'central_id' => 88,
                'name' => 'can-edit-purchase',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 89,
                'central_id' => 89,
                'name' => 'can-edit-purchase-item',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 90,
                'central_id' => 90,
                'name' => 'can-delete-purchase',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 91,
                'central_id' => 91,
                'name' => 'can-view-purchase',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 92,
                'central_id' => 92,
                'name' => 'can-view-details-purchase',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 93,
                'central_id' => 93,
                'name' => 'can-create-other-purchase',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 94,
                'central_id' => 94,
                'name' => 'can-edit-other-purchase',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 95,
                'central_id' => 95,
                'name' => 'can-edit-other-purchase-item',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 96,
                'central_id' => 96,
                'name' => 'can-delete-other-purchase',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],
            [
                'id' => 97,
                'central_id' => 97,
                'name' => 'can-view-other-purchase',
                'guard_name' => 'web',
                'group_name' => 'Purchase Management',
                'is_active' => true,
            ],

            [
                'id' => 98,
                'name' => 'can-view-other-sale',
                'guard_name' => 'web',
                'group_name' => 'Order Management'
            ],
            [
                'id' => 99,
                'name' => 'can-create-other-sale',
                'guard_name' => 'web',
                'group_name' => 'Order Management'
            ],
            [
                'id' => 100,
                'name' => 'can-edit-other-sale',
                'guard_name' => 'web',
                'group_name' => 'Order Management'
            ],
            [
                'id' => 101,
                'name' => 'can-delete-other-sale',
                'guard_name' => 'web',
                'group_name' => 'Order Management'
            ],
        ];
        foreach ($permissions as $permission) {
            Permission::create($permission);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
